root = "."
tmp_dir = "tmp"

[build]
 bin = "./tmp/main"
 cmd = "go build -tags dev -o ./tmp/main ."
  # && \
  # npx esbuild public/modules/main.js --minify --outfile=public/scripts/bundle.min.js && \
  # npx esbuild public/styles/main.css --minify --outfile=public/styles/bundle.min.css"
 delay = 20
 exclude_dir = ["assets", "tmp", "vendor", "node_modules", "sws"]
 exclude_file = []
 exclude_regex = [".*_templ.go"]
 exclude_exchange = false
 exclude_symlink = false
 full_bin = ""
 include_dir = []
 include_ext = ["go", "tpl", "tmpl", "templ", "html"]
 kill_delay = "0s"
 log = "build-errors.log"
 send_interrupt = false
 stop_on_error = true

[color]
 app = ""
 build = "yellow"
 main = "magenta"
 runner = "green"
 watcher = "cyan"

[log]
 time = false

[misc]
 clean_on_exit = false
