blank_issues_enabled: false
contact_links:
  - name: Static Web Server - Website
    url: https://static-web-server.net
    about: |
      Refer to the official website for details about installation, usage, features and examples.
  - name: Static Web Server - Community Support
    url: https://github.com/orgs/static-web-server/discussions
    about: |
      Use the discussions page if you have questions or need help.
  - name: Static Web Server Discord Community
    url: https://discord.gg/VWvtZeWAA7
    about: |
      Join to our community on Discord if you have questions, need help or want to contribute.
